apiVersion: v2
name: ingress-nginx-child-chart
description: A child chart to pull ingress-nginx chart as a dependent chart
type: application
version: 0.1.0
dependencies:
  - name: ingress-nginx
    version: 4.12.1
    repository: https://kubernetes.github.io/ingress-nginx
