apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx.fullname" . }}-configmap
  labels:
    app: {{ include "nginx.name" . }}
data:
  nginx.conf: |
    {{ .Values.configMap.nginx.conf | indent 4 }}
