apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/helloravisha/eks-ha-infra-blueprint.git'  
    targetRevision: HEAD  # or specify a branch/tag if needed
    path: observability/metrics/prometheus  
    helm:
      releaseName: metrics
      values: |
        replicaCount: 1  # Customize the values as needed
  destination: # EKS Cluster details , which is target for deployment
    server: https://2C75B8AEE83A5F41EBE3A6011BA77D47.gr7.us-east-2.eks.amazonaws.com
    namespace: metrics  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  # Automatically create the namespace if it doesn't exist
