apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pyroscope
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/helloravisha/eks-ha-infra-blueprint.git'
    targetRevision: HEAD
    path: k8s-apps/helm/profiler/pyroscope
    helm:
      releaseName: pyroscope
      values: |
        server:
          persistentVolume:
            enabled: false
          service:
            type: ClusterIP
  destination:
    server: https://2C75B8AEE83A5F41EBE3A6011BA77D47.gr7.us-east-2.eks.amazonaws.com
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
