replicaCount: 1

image:
  repository: helloravisha/encode-service
  tag: latest
  pullPolicy: Always

service:
  name: encode-service
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: encode-service.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}
