apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: {{ .Values.prometheus.prometheusSpec.replicas }}  # Use the value from values.yaml
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.45.0  # Hardcoded image tag
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"  # Config file reference
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus  # Mount the ConfigMap here
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config  # ConfigMap name from values.yaml
