apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  ports:
    - name: http
      port: 9090
      targetPort: 9090
  selector:
    app: prometheus
  type: NodePort  # You can use NodePort or ClusterIP based on your needs
