# ingress.yaml

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: order-service
  labels:
    app: order-service
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /order(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: order-service
                port:
                  number: {{ .Values.service.port }}
          - path: /hello
            pathType: Prefix
            backend:
              service:
                name: order-service
                port:
                  number: {{ .Values.service.port }}

