apiVersion: apps/v1
kind: Deployment
metadata:
  name: encode-service
  labels:
    app: encode-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: encode-service
  template:
    metadata:
      labels:
        app: encode-service
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: encode-service

      tolerations:
        - key: "critical"
          operator: "Equal"
          value: "true"
          effect: "PreferNoSchedule"  # Adding PreferNoSchedule toleration here

      containers:
        - name: encode-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
