apiVersion: apps/v1
kind: Deployment
metadata:
  name: encode-service
  namespace: encode-namespace  # Specify the namespace here
  labels:
    {{- include "encode-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "encode-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "encode-service.name" . }}
    spec:
      containers:
        - name: encode-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
