apiVersion: apps/v1
kind: Deployment
metadata:
  name: encode-service
  namespace: encode-namespace  # Specify the namespace here
  labels:
    app: encode-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: encode-service
  template:
    metadata:
      labels:
        app: encode-service
    spec:
      containers:
        - name: encode-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
