apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: encode-pdb
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app: encode-service
