# service.yaml

apiVersion: v1
kind: Service
type: NodePort
metadata:
  name: encode-service
  labels:
    app: encode-service
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
  selector:
    app: encode-service

