apiVersion: v2
name: prometheus-stack
description: A Helm chart to deploy Prometheus and Node Exporter via ArgoCD
type: application
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack
    version: 55.5.0
    repository: https://prometheus-community.github.io/helm-charts
