prometheus:
  prometheusSpec:
    scrapeInterval: "15s"
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    retention: 2d

nodeExporter:
  enabled: false
  service:
    port: 9100

kube-state-metrics:
  enabled: false

grafana:
  enabled: false  # Enable if you want Grafana too

defaultRules:
  create: true
