# values.yaml

# Prometheus Configuration
prometheus:
  prometheusSpec:
    replicas: 1
    serviceAccountName: prometheus
    scrapeInterval: "15s"
    retention: "2d"


# Prometheus ConfigMap
prometheusConfig:
  prometheusYml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'node'
        scrape_interval: 30s
        metrics_path: /metrics
        static_configs:
          - targets: ['node-exporter:9100']
