pyroscope:
  server:
    persistentVolume:
      enabled: false  # Turn on in production
    service:
      type: ClusterIP

ingress:
  enabled: true
  host: a2074f890eaab46f7a87182611724d46-1127988196.us-east-2.elb.amazonaws.com  # Replace with your actual domain
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    kubernetes.io/ingress.class: nginx
agent:
  enabled: true
  appName: encode-service
  serverURL: http://pyroscope.observability.svc.cluster.local:4040  # Internal cluster service URL
  logLevel: debug  # Optional: helps with troubleshooting
    # scrapeInterval: 10s  # Optional: adjust how often to scrape
    

